CREATE TABLE “C##OMCUSER”.“FLIGHT” (
	“ID” NUMBER(6,0) NOT NULL PRIMARY KEY,
	“AIRLINE” VARCHAR2(20),
	“DEPARTURE” VARCHAR2(25),
	“DESTINATION” VARCHAR2(25),
	“FLYTIME” VARCHAR2(25),
	“CLASS” VARCHAR2(25),
	“OFF” VARCHAR2(10),
	“ORIGINAL” VARCHAR2(25)
);
insert into flight(ID,AIRLINE,DEPARTURE,DESTINATION,FLYTIME,CLASS,OFF,ORIGINAL) values(‘123455’,‘tokyo’,‘2021/3/25’,‘osaka’,‘11:20’,‘business’,‘ontime’,‘fly’)
